version: "3.8"

services:
  # Backend FastAPI service
  backend:
    build:
      context: ../backend
      dockerfile: Dockerfile
    container_name: career-catalyst-backend
    restart: unless-stopped
    volumes:
      - ../backend:/app
      - backend_data:/app/data
    environment:
      - MONGO_URI=mongodb://mongodb:27017/
      - DATABASE_NAME=career_catalyst
      - GEMINI_API_KEY=${GEMINI_API_KEY}
      - DEBUG=True
      - ENVIRONMENT=development
    depends_on:
      - mongodb
    networks:
      - app-network

  # Frontend service
  frontend:
    build:
      context: ../modules/module5_frontend
      dockerfile: Dockerfile
    container_name: career-catalyst-frontend
    restart: unless-stopped
    volumes:
      - ../modules/module5_frontend:/app
      - /app/node_modules
    environment:
      - NEXT_PUBLIC_API_URL=http://localhost/api
      - NODE_ENV=development
    networks:
      - app-network

  # MongoDB database service
  mongodb:
    image: mongo:6.0
    container_name: career-catalyst-mongodb
    restart: unless-stopped
    volumes:
      - mongodb_data:/data/db
    environment:
      - MONGO_INITDB_ROOT_USERNAME=${MONGO_ROOT_USERNAME:-admin}
      - MONGO_INITDB_ROOT_PASSWORD=${MONGO_ROOT_PASSWORD:-password}
    networks:
      - app-network

  # Nginx reverse proxy
  nginx:
    build:
      context: ./nginx
      dockerfile: Dockerfile
    container_name: career-catalyst-nginx
    restart: unless-stopped
    ports:
      - "80:80"
    depends_on:
      - backend
      - frontend
    networks:
      - app-network

networks:
  app-network:
    driver: bridge

volumes:
  mongodb_data:
  backend_data:
